# Copyright (c) 2014 GOTO Hidenori <hidenorigoto@gmail.com>,
# All rights reserved.
#
# This file is part of PHPMentorsValidatorBundle.
#
# This program and the accompanying materials are made available under
# the terms of the BSD 2-Clause License which accompanies this
# distribution, and is available at http://opensource.org/licenses/BSD-2-Clause

parameters:
    phpmentors_validator.service_callback.class: PHPMentors\ValidatorBundle\Constraints\ServiceCallbackValidator

services:
    phpmentors_validator.service_callback:
        class: %phpmentors_validator.service_callback.class%
        calls:
            - [ setContainer, ["@service_container"] ]
        tags:
            - { name: validator.constraint_validator, alias: PHPMentorsServiceCallbackValidator }
